# 共通設定
[config]
current_dir="Locate"

# 各言語のテキスト情報
# 日本語の各テキストグループ
[locate.JP.default]
json="Text.json"
# デバッグ用のテキスト
# TODO: リリースの場合はロードしないようにする
[locate.JP.debug]
json="Debug.json"

# (Test)英語の各テキストグループ
[locate.EN.default]
json="Text.json"

